name: 'Obsidian Renderer'
description: 'Crudely render an obsidian vault to Github pages'
author: 'Eroxl'
branding:
  icon: file-text
  color: green

inputs:
  NOTES_ROOT_DIR:
    description: 'Location to obsidian vault'
    required: true
    default: './'
  PREAMBLE_PATH:
    description: 'Location to LaTeX preamble'
    required: true
    default: './preamble.sty' 
  DESMOS_CACHE_PATH:
    description: 'Location of the cached desmos graphs' 
    required: true
    default: './desmos-cache/'

runs:
  using: 'composite'
  steps:
    - name: Checkout files
      uses: actions/checkout@v3

    - name: Checkout renderer
      uses: actions/checkout@v3
      with:
        name: eroxl/Notes-Renderer
        path: 'renderer'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        working-directory: ./renderer

    - name: Install Dependencies
      shell: bash
      run: cd ./renderer/ && yarn install --immutable
      with:
        working-directory: ./renderer

    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
        static_site_generator: next 
        working-directory: ./renderer 

    - name: Build with NextJS
      shell: bash
      run: yarn build
      with:
        working-directory: ./renderer

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out
        working-directory: ./renderer

    - name: Publish
      id: deployment
      uses: actions/deploy-pages@v4


permissions:
  contents: read
  id-token: write
  actions: read
  checks: read
  deployments: write
  issues: write
  metadata: read
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write