name: 'Obsidian Renderer'
description: 'Crudely render an obsidian vault to Github pages'
author: 'Eroxl'
branding:
  icon: file-text
  color: green

inputs:
  NOTES_ROOT_PATH:
    description: 'Location to obsidian vault'
    required: true
    default: './'
  PREAMBLE_PATH:
    description: 'Location to LaTeX preamble'
    required: true
    default: './preamble.sty' 
  DESMOS_CACHE_PATH:
    description: 'Location of the cached desmos graphs' 
    required: true
    default: './desmos-cache/'

runs:
  using: 'composite'
  steps:
    - name: Checkout files
      uses: actions/checkout@v4

    - name: Checkout renderer
      uses: actions/checkout@v4
      with:
        repository: eroxl/Notes-Renderer
        path: 'renderer'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: renderer/yarn.lock

    - name: Install Dependencies
      shell: bash
      run: cd ./renderer/ && yarn install --immutable

    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
        static_site_generator: next 

    - name: Build with NextJS
      shell: bash
      run: cd ./renderer/ && yarn build
      env:
        INPUT_NOTES_ROOT_PATH: ${{ inputs.NOTES_ROOT_PATH }}
        INPUT_PREAMBLE_PATH: ${{ inputs.PREAMBLE_PATH }}
        INPUT_DESMOS_CACHE_PATH: ${{ inputs.DESMOS_CACHE_PATH }}

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: renderer/out

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}


permissions:
  contents: read
  id-token: write
  actions: read
  checks: read
  deployments: write
  issues: write
  metadata: read
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write