name: 'Obsidian Renderer'
description: 'Crudely render an obsidian vault to Github pages'
author: 'Eroxl'
branding:
  icon: file-text
  color: green

permissions:
  contents: read
  pages: write
  id-token: write

inputs:
  NOTES_ROOT_DIR:
    description: 'Location to obsidian vault'
    required: true
    default: './'
  PREAMBLE_PATH:
    description: 'Location to LaTeX preamble'
    required: true
    default: './preamble.sty' 
  DESMOS_CACHE_PATH:
    description: 'Location of the cached desmos graphs' 
    required: true
    default: './desmos-cache/'
  ROOT_PATH:
    description: 'The root path where the files are hosted' 
    required: true
    default: '/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        shell: bash
        run: yarn install --immutable

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
        
      - name: Build with NextJS
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ env.INPUT_ROOT_PATH }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
